Controllers/PageControllers/SaleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SupermarketAnalyzer.Models;

namespace SupermarketAnalyzer.Controllers.PageControllers
{
    [Authorize(Roles = $"{nameof(Customer)}, {nameof(Employee)}")]
    public class SaleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/PageControllers/SoldController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupermarketAnalyzer.Models;

namespace SupermarketAnalyzer.Controllers.PageControllers
{
    [Authorize(Roles = $"{nameof(Customer)}, {nameof(Employee)}")]
    public class SoldController : Controller
    {

        private readonly SupermarketAnalyzer.Data.SupermarketDbContext _dbContext;
        public SoldController(SupermarketAnalyzer.Data.SupermarketDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddSold(string pay, DateTime saleDate, int empId, int custId, int prodId)
        {
            if (saleDate == null)
            {
                saleDate = DateTime.Now;
            }

            var param0 = new Microsoft.Data.SqlClient.SqlParameter("@_pay", pay);
            var param1 = new Microsoft.Data.SqlClient.SqlParameter("@_saleDate", saleDate);
            var param2 = new Microsoft.Data.SqlClient.SqlParameter("@_cust", custId);
            var param3 = new Microsoft.Data.SqlClient.SqlParameter("@_emp", empId);
            var param4 = new Microsoft.Data.SqlClient.SqlParameter("@_pr", prodId);
            var query = "EXEC BuyProduct @Pay = @_pay, @SaleDate = @_saleDate, @CustId = @_cust, @EmpId = @_emp, @PrId = @_pr;";            
            int row = _dbContext.Database.ExecuteSqlRaw(query, param0, param1, param2, param3, param4);

            return Ok();
        }
    }
}

Controllers/PageControllers/StatisticController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupermarketAnalyzer.Models;

namespace SupermarketAnalyzer.Controllers.PageControllers
{
    [Authorize(Roles = $"{nameof(Employee)}")]
    public class StatisticController : Controller
    {
		private readonly SupermarketAnalyzer.Data.SupermarketDbContext _dbContext;

		public double Result { get; set; }

		[BindProperty(Name = "StartDate")]
		public DateTime StartDate { get; set; }

		[BindProperty(Name = "EndDate")]
		public DateTime EndDate { get; set; }

		public StatisticController(SupermarketAnalyzer.Data.SupermarketDbContext dbContext)
		{
			_dbContext = dbContext;
		}
		public IActionResult Index()
        {
            return View();
        }

		public IActionResult StoreStat()
		{
			return View();
		}

		public IActionResult EmpStat() 
		{
			return View();
		}


        public IActionResult CalcProfit(DateTime StartDate, DateTime EndDate)
		{
			if (StartDate < EndDate)
			{
				var param0 = new Microsoft.Data.SqlClient.SqlParameter("@StartDate", StartDate);
				var param1 = new Microsoft.Data.SqlClient.SqlParameter("@EndDate", EndDate);
				var query = "SELECT dbo.CalculateProfit(@StartDate, @EndDate)";
				try
				{
					var _Result = _dbContext.Database.SqlQueryRaw<double>(query, param0, param1);
					Result = _Result.AsEnumerable().FirstOrDefault();
				}
				catch (Exception ex)
				{
					Result = 0;
				}
			}

			return Ok(Result);
		}
	}
}

Controllers/PageControllers/SupplyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SupermarketAnalyzer.Models;

namespace SupermarketAnalyzer.Controllers.PageControllers
{
    [Authorize(Roles = $"{nameof(Employee)}")]
    public class SupplyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SupermarketAnalyzer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SupermarketAnalyzer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SupermarketAnalyzer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="Index">Statistic</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="StoreStat">Store Statistic</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Statistic" asp-action="EmpStat">Employee Statistic</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Sale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sold" asp-action="Index">Sold</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Supply" asp-action="Index">Supply</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SupermarketAnalyzer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>